#!/bin/bash

if [[ -n "$ON_AWS" ]]; then
  cd ~
  npm install @cumulus/test-data

  # start ftp
  sudo rm -rf /home/vsftpd
  sudo ln -s /home/circleci/project/packages/test-data /home/vsftpd
  sudo service vsftpd start || true

  # start http service
  sudo rm -rf /var/www/html
  sudo ln -s /home/circleci/project/packages/test-data /var/www/html
  sudo service apache2 start

  # start sftp service
  sudo bash /usr/sbin/sftp.sh user:password
  sudo cp -r /home/circleci/project/packages/test-data/* /home/user/
else
  sudo service vsftpd start || true
  sudo service apache2 start
  sudo bash /usr/sbin/sftp.sh user:password
fi

tail -f /dev/null