#!/bin/bash

if [[ -n "$ON_AWS" ]]; then

  if [[ -n "$TEST_DATA_S3_PATH" ]]; then
    mkdir -p node_modules/@cumulus/test-data/
    aws s3 cp --recursive $TEST_DATA_S3_PATH node_modules/@cumulus/test-data/ 
  else
    npm install @cumulus/test-data
  fi

  # start ftp
  sudo rm -rf /home/vsftpd
  sudo ln -s /home/circleci/node_modules/@cumulus/test-data /home/vsftpd
  sudo service vsftpd start || true

  # start http service
  sudo rm -rf /var/www/html
  sudo ln -s /home/circleci/node_modules/@cumulus/test-data /var/www/html
  sudo service apache2 start

  # start sftp service
  sudo bash /usr/sbin/sftp.sh user:password
  sudo cp -r /home/circleci/node_modules/@cumulus/test-data/* /home/user/
else
  sudo service vsftpd start || true
  sudo service apache2 start
  sudo bash /usr/sbin/sftp.sh user:password
fi

tail -f /dev/null